# Generated by Django 5.0.1 on 2024-06-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='friends_object',
        ),
        migrations.AddField(
            model_name='request',
            name='friends_object',
            field=models.ManyToManyField(to='api.profile'),
        ),
    ]
