# Generated by Django 5.0.1 on 2024-06-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_request_friends_object_request_friends_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Friends',
        ),
    ]
