# Generated by Django 5.0.1 on 2024-06-06 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_request_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friends_object',
        ),
        migrations.AddField(
            model_name='friends',
            name='friends_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
            preserve_default=False,
        ),
    ]
