# Generated by Django 5.0.1 on 2024-06-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_friends_friends_object_friends_friends_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='last_request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
