# Generated by Django 5.0.1 on 2024-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_friends_last_request_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='last_request_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
